# CMake generated Testfile for 
# Source directory: /Users/Jonathan/Documents/GitHub/organicmaps
# Build directory: /Users/Jonathan/Documents/GitHub/organicmaps/omim-build-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[OmimStartTestServer]=] "start_server.py")
set_tests_properties([=[OmimStartTestServer]=] PROPERTIES  FIXTURES_SETUP "TestServer" LABELS "omim-fixture" WORKING_DIRECTORY "/Users/Jonathan/Documents/GitHub/organicmaps/tools/python/test_server" _BACKTRACE_TRIPLES "/Users/Jonathan/Documents/GitHub/organicmaps/cmake/OmimTesting.cmake;11;add_test;/Users/Jonathan/Documents/GitHub/organicmaps/cmake/OmimTesting.cmake;0;;/Users/Jonathan/Documents/GitHub/organicmaps/CMakeLists.txt;74;include;/Users/Jonathan/Documents/GitHub/organicmaps/CMakeLists.txt;0;")
add_test([=[OmimStopTestServer]=] "stop_server.py")
set_tests_properties([=[OmimStopTestServer]=] PROPERTIES  FIXTURES_CLEANUP "TestServer" LABELS "omim-fixture" WORKING_DIRECTORY "/Users/Jonathan/Documents/GitHub/organicmaps/tools/python/test_server" _BACKTRACE_TRIPLES "/Users/Jonathan/Documents/GitHub/organicmaps/cmake/OmimTesting.cmake;16;add_test;/Users/Jonathan/Documents/GitHub/organicmaps/cmake/OmimTesting.cmake;0;;/Users/Jonathan/Documents/GitHub/organicmaps/CMakeLists.txt;74;include;/Users/Jonathan/Documents/GitHub/organicmaps/CMakeLists.txt;0;")
subdirs("3party")
subdirs("base")
subdirs("coding")
subdirs("descriptions")
subdirs("drape")
subdirs("drape_frontend")
subdirs("editor")
subdirs("ge0")
subdirs("generator/mwm_diff")
subdirs("geometry")
subdirs("indexer")
subdirs("kml")
subdirs("map")
subdirs("cppjansson")
subdirs("platform")
subdirs("routing")
subdirs("routing_common")
subdirs("search")
subdirs("shaders")
subdirs("storage")
subdirs("tracking")
subdirs("traffic")
subdirs("transit")
subdirs("feature_list")
subdirs("generator")
subdirs("openlr")
subdirs("poly_borders")
subdirs("topography_generator")
subdirs("track_analyzing")
subdirs("track_generator")
subdirs("qt")
subdirs("skin_generator")
subdirs("qt_tstfrm")
